# Generated by Django 2.0.2 on 2018-03-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='username',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
