# Generated by Django 2.0.2 on 2018-03-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_auto_20180310_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('company', models.CharField(max_length=15)),
                ('model_name', models.CharField(max_length=15)),
                ('car_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=3)),
                ('hour_price', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
