# Generated by Django 2.0.2 on 2018-03-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180319_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='images',
            field=models.CharField(max_length=25),
        ),
    ]
