# Generated by Django 2.0.2 on 2018-03-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180319_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='availability',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
