# Generated by Django 2.0.2 on 2018-04-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_cars_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
