# Generated by Django 2.0.1 on 2018-04-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20180404_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='car_id',
            new_name='registration_no',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='car_id',
            new_name='registration_no',
        ),
    ]
