# Generated by Django 2.0.1 on 2018-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20180405_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='availability',
            field=models.CharField(default='available', max_length=10),
        ),
    ]
